# Tipo  Booleano

print(type(True))
print(type(False))
print((' =-') *10)
print(not True)
print(not False)
print((' =-') *10)
print(True or False)
print(True or True)
print(False or True)
print(False or False)
print((' =-') *10)
print(True and False)
print(True and True)
print(False and True)
print(False and False)
print((' Maior igual <=    ou menor igual <=      ') *2)
print(5 > 6)
print(5 < 6)
print(5 >= 6)
print(5 <= 6)
print(6 <= 6)
print((' igual ==    ') *3)
print(6 == 6)
print(7 == 6)
print((' diferente !=    ') *3)
print(6 != 6)
print(6 != 86)
print('   perguntar se está em um intervalo    ')
n = 6
print(1< n and n < 5)
print(' outro modo ')
print(1< n < 5)
